baseURL = 'https://ivanhan0511.github.io/'
languageCode = 'en-us'
title = 'IVAN BLOG'
theme = "hugo-tranquilpeak-theme"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  dateFormat = "2 January 2006"
  header_image = "images/A.jpg"
  title = "Software Engineering"
  slogan = "$ grep -rni \"The how's and why's\" ."
  SEOTitle = "Ivan Han Blog"
  keywords = ["Ivan", "Python", "C/C++", "Coffee", "Bass"]

  # Sidebar settings
  sidebar_about_description = "Father, Husband, Skier, Cyclist, and, oh yeah, Software Developer"
  sidebar_avatar = "images/MeAtJackson.jpeg"
  about_me = true

  featured_tags = true 
  featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "images/404-bg.jpg"
  title_404 = "We couldn't find what you were looking for..."

  omit_categories = false

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = true
  email          = "ivanhan0511@gmail.com"
  github         = "https://github.com/ivanhan0511"
